name: Flutter Web Github Pages

on:
  push:
    branch: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.12.x'
          channel: 'beta'

      - name: Upgrade Flutter
        run: flutter upgrade

      - name: Enable Web
        run: flutter config --enable-web

      - name: Install Dependencies
        run: flutter packages get

      - name: Build Web
        run: flutter build web
